In [1]:
import numpy as np

vec = np.random.randint(1, 21, 15)
print("Vector:\n", vec)

mat = vec.reshape(3, 5)
print("\nReshaped to 3x5:\n", mat)

print("\nShape:", mat.shape)

for i in range(mat.shape[0]):
    mat[i, np.argmax(mat[i])] = 0
print("\nAfter replacing row max with 0:\n", mat)


Original Vector:
 [13 12 19 20 20  6 20 18  7 14 13 10  3  7 18]

Reshaped to 3x5:
 [[13 12 19 20 20]
 [ 6 20 18  7 14]
 [13 10  3  7 18]]

Shape: (3, 5)

After replacing row max with 0:
 [[13 12 19  0 20]
 [ 6  0 18  7 14]
 [13 10  3  7  0]]


In [5]:
# Create 4x3 array with 4-byte integers
array_4x3 = np.zeros((4, 3), dtype=np.int32)

print("Array:\n", array_4x3)
print("Shape:", array_4x3.shape)
print("Type:", type(array_4x3))
print("Data type:", array_4x3.dtype)


Array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data type: int32


In [3]:

matrix = np.array([[3, -2], [1, 0]])

eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:", eigenvalues)
print("Right Eigenvectors:\n", eigenvectors)


Eigenvalues: [2. 1.]
Right Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [7]:

arr = np.array([[0, 1, 2], [3, 4, 5]])

diag_sum = np.trace(arr)

print("Sum of diagonal elements:", diag_sum)


Sum of diagonal elements: 4


In [8]:

original = np.array([[1, 2], [3, 4], [5, 6]])

reshaped = original.reshape(2, 3)

print("Original 3x2:\n", original)
print("Reshaped to 2x3:\n", reshaped)


Original 3x2:
 [[1 2]
 [3 4]
 [5 6]]
Reshaped to 2x3:
 [[1 2 3]
 [4 5 6]]
